### ISSUE TITLE
Error: Cannot find module './index.ts'

### ISSUE THREAD

**Issue by mgifford** [autogram-is/create-spidergram#1]
Not sure what I'm doing wrong, but after running (first two seem to be not giving me errors)

```
% npx create-spidergram  
% npm install  
% npm run crawl https://www.whitehouse.gov
```

I get this error here:

```
> cms.gov@0.7.2 crawl
> ts-node index.ts https://www.whitehouse.gov

node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './index.ts'
Require stack:
- /Users/mgifford/spidergram-test/imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at requireResolveNonCached (/Users/mgifford/spidergram-test/node_modules/ts-node/dist/bin.js:549:16)
    at getProjectSearchDir (/Users/mgifford/spidergram-test/node_modules/ts-node/dist/bin.js:519:40)
    at phase3 (/Users/mgifford/spidergram-test/node_modules/ts-node/dist/bin.js:267:27)
    at bootstrap (/Users/mgifford/spidergram-test/node_modules/ts-node/dist/bin.js:47:30)
    at main (/Users/mgifford/spidergram-test/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/mgifford/spidergram-test/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mgifford/spidergram-test/imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v18.12.1
```

**Comment by eaton** [comment]
Thanks! This brought a couple of issues in the previous release to our attention and they should be squashed with the new 0.8.0 branch.

`npx create-spidergram@latest` should do the trick even if there are issues with the cached version.

As an added bonus, the new 'report' example template includes sample code for generating site hierarchy reports and Excel spreadsheet exports from crawl data.
